/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zaidd
 */
public class adminPage extends javax.swing.JFrame {

    /**
     * Creates new form adminPage
     * 
     */
      Connection conn= null;
       ResultSet rs= null;
        PreparedStatement ps= null;
    public adminPage() {
        initComponents();
        updateBooktable();
        updateGuesttable();
        updateLibrariantable();
        
    }
     public void updateLibrariantable(){
     try{
            conn=dbConnection.ConnectDB();
            String sql= "select * from librariann";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            ResultSetMetaData Datamata= rs.getMetaData();
            int Column = Datamata.getColumnCount();
            DefaultTableModel dtm= new DefaultTableModel();
            Vector Column_Name= new Vector();
            Vector row_data= new Vector();
            for(int i=1; i<Column; i++){
            Column_Name.addElement(Datamata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(Column_Name);
            while (rs.next()){
            row_data= new Vector();
            for(int j=1;j<Column; j++){
            row_data.addElement(rs.getString(j));
            }
            dtm.addRow(row_data);
            }
           LibrarianTable.setModel(dtm);
           }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
        }
     }
     public void updateBooktable(){
     try{
            conn=dbConnection.ConnectDB();
            String sql= "select BookID, bookISBN, bookTitle,BookStatus, authorName  from book";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            ResultSetMetaData Datamata= rs.getMetaData();
            int Column = Datamata.getColumnCount();
            DefaultTableModel dtm= new DefaultTableModel();
            Vector Column_Name= new Vector();
            Vector row_data= new Vector();
            for(int i=1; i<Column; i++){
            Column_Name.addElement(Datamata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(Column_Name);
            while (rs.next()){
            row_data= new Vector();
            for(int j=1;j<Column; j++){
            row_data.addElement(rs.getString(j));
            }
            dtm.addRow(row_data);
            }
           BookTable.setModel(dtm);
           }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
        }
     }
     public void updateGuesttable(){
     try{
            conn=dbConnection.ConnectDB();
            String sql= "select * from guest";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            ResultSetMetaData Datamata= rs.getMetaData();
            int Column = Datamata.getColumnCount();
            DefaultTableModel dtm= new DefaultTableModel();
            Vector Column_Name= new Vector();
            Vector row_data= new Vector();
            for(int i=1; i<Column; i++){
            Column_Name.addElement(Datamata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(Column_Name);
            while (rs.next()){
            row_data= new Vector();
            for(int j=1;j<Column; j++){
            row_data.addElement(rs.getString(j));
            }
            dtm.addRow(row_data);
            }
           GuestTable.setModel(dtm);
           }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        BookID = new javax.swing.JTextField();
        BookISBN = new javax.swing.JTextField();
        BookTitle = new javax.swing.JTextField();
        BookAuthor = new javax.swing.JTextField();
        BookStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AddBookBTN = new javax.swing.JButton();
        EditBook = new javax.swing.JButton();
        DeleteBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        librarianID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        librarianFN = new javax.swing.JTextField();
        librarianLN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        librarianUN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        librarianP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddLibrarian = new javax.swing.JButton();
        EditLibrarian = new javax.swing.JButton();
        DeleteLibrarian = new javax.swing.JButton();
        librarianEA = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        librarianPN = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        SearchLibrarian = new javax.swing.JTextField();
        SearchLibrarianButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        LibrarianTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        guestID = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        emailAddress = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        AddNewGuest = new javax.swing.JButton();
        EditNewGuest = new javax.swing.JButton();
        deleteGuest = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        searchGuestTF = new javax.swing.JTextField();
        searchGuest = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        GuestTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        guestReport = new javax.swing.JButton();
        TotalBooksReport = new javax.swing.JButton();
        TotalBorrowedBookReport = new javax.swing.JButton();
        totalAvailableBooksReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportArea = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        TFTRY = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        ExitTheSystem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System: Admin Page");

        jLabel7.setText("Search Book");

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        BookISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookISBNActionPerformed(evt);
            }
        });

        BookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTitleActionPerformed(evt);
            }
        });

        BookStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Available", "Borrowed" }));

        jLabel8.setText("Book Status");

        jLabel9.setText("Author");

        jLabel10.setText("Title");

        jLabel11.setText("ISBN");

        jLabel12.setText("Book ID");

        AddBookBTN.setText("Add");
        AddBookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookBTNActionPerformed(evt);
            }
        });

        EditBook.setText("Edit/Check In/Check out Books");
        EditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBookActionPerformed(evt);
            }
        });

        DeleteBook.setText("Delete");
        DeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookActionPerformed(evt);
            }
        });

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(BookTable);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(searchTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BookID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BookISBN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BookTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BookAuthor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BookStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AddBookBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(EditBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DeleteBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5))
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BookStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 309, Short.MAX_VALUE)
                                    .addComponent(BookAuthor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BookTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BookISBN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BookID, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(AddBookBTN)
                                .addGap(27, 27, 27)
                                .addComponent(EditBook)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteBook)))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(BookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(BookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(BookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBookBTN)
                    .addComponent(EditBook)
                    .addComponent(DeleteBook)
                    .addComponent(jButton1))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book", jLayeredPane1);

        jLabel1.setText("Librarian ID");

        jLabel2.setText("First Name");

        librarianLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianLNActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        jLabel4.setText("UserName");

        librarianUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianUNActionPerformed(evt);
            }
        });

        jLabel5.setText("Password");

        jLabel6.setText("emailAddress");

        AddLibrarian.setText("Add");
        AddLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLibrarianActionPerformed(evt);
            }
        });

        EditLibrarian.setText("Edit");
        EditLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditLibrarianActionPerformed(evt);
            }
        });

        DeleteLibrarian.setText("Delete");
        DeleteLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLibrarianActionPerformed(evt);
            }
        });

        jLabel22.setText("phoneNumber");

        jLabel25.setText("Search");

        SearchLibrarianButton.setText("Search");
        SearchLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchLibrarianButtonActionPerformed(evt);
            }
        });

        LibrarianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(LibrarianTable);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(librarianID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(librarianFN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(librarianLN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(librarianUN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(librarianP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(AddLibrarian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EditLibrarian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(DeleteLibrarian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(librarianEA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(librarianPN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(SearchLibrarian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(SearchLibrarianButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel25))
                                .addGap(52, 52, 52)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(librarianID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(librarianLN, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(librarianFN, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(librarianUN, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(librarianP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel22))
                                        .addGap(52, 52, 52)
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(librarianEA)
                                            .addComponent(librarianPN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(SearchLibrarian)))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddLibrarian)
                                .addGap(10, 10, 10)
                                .addComponent(EditLibrarian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteLibrarian)
                                .addGap(192, 192, 192)))
                        .addGap(31, 31, 31)
                        .addComponent(SearchLibrarianButton)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(SearchLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchLibrarianButton))
                .addGap(22, 22, 22)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(librarianID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(librarianFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(librarianLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(librarianUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(librarianP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(librarianEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(librarianPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddLibrarian)
                    .addComponent(EditLibrarian)
                    .addComponent(DeleteLibrarian)
                    .addComponent(jButton2))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("librarian ", jLayeredPane3);

        jLabel13.setText("Guest ID");

        jLabel14.setText("First Name");

        jLabel15.setText("Last Name");

        jLabel18.setText("Gender");

        jLabel19.setText("Email Address");

        jLabel20.setText("Phone Number");

        jLabel21.setText("Address");

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Male", "Female" }));

        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });

        AddNewGuest.setText("Add");
        AddNewGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewGuestActionPerformed(evt);
            }
        });

        EditNewGuest.setText("Edit");
        EditNewGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNewGuestActionPerformed(evt);
            }
        });

        deleteGuest.setText("Delete");
        deleteGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGuestActionPerformed(evt);
            }
        });

        jLabel24.setText("Search");

        searchGuest.setText("Search");
        searchGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGuestActionPerformed(evt);
            }
        });

        GuestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(GuestTable);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(guestID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(firstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(gender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(emailAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(phoneNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Address, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(AddNewGuest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(EditNewGuest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(deleteGuest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(searchGuestTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(searchGuest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel24))
                        .addGap(35, 35, 35)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(guestID, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(firstName)
                                    .addComponent(lastName))
                                .addGap(28, 28, 28)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(20, 20, 20)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailAddress)
                                    .addComponent(phoneNumber)
                                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(searchGuestTF)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddNewGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditNewGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(searchGuest)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(searchGuestTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGuest))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(guestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewGuest)
                    .addComponent(EditNewGuest)
                    .addComponent(deleteGuest)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register Guest ", jLayeredPane2);

        guestReport.setText("Report of All Gesut Male/Female");
        guestReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestReportActionPerformed(evt);
            }
        });

        TotalBooksReport.setText("Report of the total Number of  Book  ");
        TotalBooksReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBooksReportActionPerformed(evt);
            }
        });

        TotalBorrowedBookReport.setText("Report of all Borrowed Book");
        TotalBorrowedBookReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBorrowedBookReportActionPerformed(evt);
            }
        });

        totalAvailableBooksReport.setText("Report of all  Availabe Book");
        totalAvailableBooksReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAvailableBooksReportActionPerformed(evt);
            }
        });

        ReportArea.setColumns(20);
        ReportArea.setRows(5);
        jScrollPane1.setViewportView(ReportArea);

        jLabel23.setText("Report Type/Description");

        jLayeredPane4.setLayer(guestReport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(TotalBooksReport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(TotalBorrowedBookReport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(totalAvailableBooksReport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(TFTRY, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(guestReport, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalBooksReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalBorrowedBookReport, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(totalAvailableBooksReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(TFTRY))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(TFTRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestReport)
                    .addComponent(TotalBooksReport)
                    .addComponent(TotalBorrowedBookReport)
                    .addComponent(totalAvailableBooksReport))
                .addContainerGap(364, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generate Report", jLayeredPane4);

        jMenu1.setText("File");

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_HOME, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        ExitTheSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        ExitTheSystem.setText("Exit");
        ExitTheSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitTheSystemActionPerformed(evt);
            }
        });
        jMenu1.add(ExitTheSystem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librarianLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librarianLNActionPerformed

    private void librarianUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librarianUNActionPerformed

    private void BookISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookISBNActionPerformed

    private void BookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookTitleActionPerformed

    private void AddBookBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookBTNActionPerformed
        book addNew = new book();
        addNew.setBookISBN(BookISBN.getText());
        addNew.setBookTitle(BookTitle.getText());
        addNew.setAuthorName(BookAuthor.getText());
        addNew.setBookStatus(BookStatus.getSelectedItem().toString());
        addNew.AddBook();
        updateBooktable();

    }//GEN-LAST:event_AddBookBTNActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void EditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookActionPerformed
    
        book updateRecord = new book();
        updateRecord.setBookID(BookID.getText());
        updateRecord.setBookISBN(BookISBN.getText());
        updateRecord.setBookTitle(BookTitle.getText());
        updateRecord.setAuthorName(BookAuthor.getText());
        updateRecord.setBookStatus(BookStatus.getSelectedItem().toString());
        updateRecord.EditBook();
        updateBooktable();
        updateBooktable();

    }//GEN-LAST:event_EditBookActionPerformed

    private void DeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you Sure That you Want to delete the selected item", "delete" ,JOptionPane.YES_NO_OPTION);
        if(p==0){
        book updateRecord = new book();
       updateRecord.setBookID(BookID.getText());
       updateRecord.DeletBook();
       updateBooktable();
        }
    }//GEN-LAST:event_DeleteBookActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
               
               book searchRecord = new book();
               searchRecord.setSearchTF(searchTF.getText());
               searchRecord.SearchBook();
               
                String add1=searchRecord.getBookID();
                BookID.setText(add1);
                String add2=searchRecord.getBookISBN();
                BookISBN.setText(add2);
                String add3=searchRecord.getBookTitle();
                BookTitle.setText(add3);
                String add4=searchRecord.getAuthorName();
                BookAuthor.setText(add4);
                String add5=searchRecord.getBookStatus();
                BookStatus.setSelectedItem(add5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void guestReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestReportActionPerformed
      book report=new book();
     report.ReportTotalRegisteredGuest();
     int add1=report.getTotalRegisteredGuest();
     String y = String.valueOf(add1);
     String display="hi";
     TFTRY.setText("The total Number of the Registered Guest as Displayed  Below:");
     ReportArea.setText(y);
          
              
    }//GEN-LAST:event_guestReportActionPerformed

    private void TotalBooksReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBooksReportActionPerformed
     book report=new book();
     report.ReportTotalNumberOFBook();
     int add1=report.getTotalBook();
     String y = String.valueOf(add1);
     String display="hi";
     TFTRY.setText("The total Number of the Book are as Displayed in Below:");
     ReportArea.setText(y);
       
    }//GEN-LAST:event_TotalBooksReportActionPerformed

    private void AddNewGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewGuestActionPerformed

        guest addGuest=new guest();
        addGuest.setFirstName(firstName.getText());
        addGuest.setLastName(lastName.getText());

        addGuest.setGender(gender.getSelectedItem().toString());
        addGuest.setEmailAddress(emailAddress.getText());
        addGuest.setPhoneNumber(phoneNumber.getText());
        addGuest.setAddress(Address.getText());
        addGuest.registerGuest();
        updateGuesttable();
    }//GEN-LAST:event_AddNewGuestActionPerformed

    private void AddLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLibrarianActionPerformed
  
    librarian addLibrarian= new librarian();
    addLibrarian.setFirstName(librarianFN.getText());
    addLibrarian.setLastName(librarianLN.getText());
    addLibrarian.setUsername(librarianUN.getText());
    addLibrarian.setPassword(librarianP.getText());
    addLibrarian.setEmailAddress(librarianEA.getText());
    addLibrarian.setPhoneNumber(librarianPN.getText());
     addLibrarian.AddLibrarian();
     updateLibrariantable();
        
    }//GEN-LAST:event_AddLibrarianActionPerformed

    private void EditLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLibrarianActionPerformed
    librarian updateLibrarian = new librarian();
    updateLibrarian.setLibrarianID(librarianID.getText());
    updateLibrarian.setFirstName(librarianFN.getText());
    updateLibrarian.setLastName(librarianLN.getText());
    updateLibrarian.setUsername(librarianUN.getText());
    updateLibrarian.setPassword(librarianP.getText());
    updateLibrarian.setEmailAddress(librarianEA.getText());
    updateLibrarian.setPhoneNumber(librarianPN.getText());
    updateLibrarian.EditLibrarian();
    updateLibrariantable();
               
    }//GEN-LAST:event_EditLibrarianActionPerformed

    private void DeleteLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLibrarianActionPerformed
        
       int p = JOptionPane.showConfirmDialog(null, "Are you Sure That you Want to delete the selected item", "delete" ,JOptionPane.YES_NO_OPTION);
        if(p==0){
        librarian deleteLibrarian = new librarian();
       deleteLibrarian.setLibrarianID(librarianID.getText());
       deleteLibrarian.DeleteLibrarian();
       updateLibrariantable();
        }
    }//GEN-LAST:event_DeleteLibrarianActionPerformed

    private void SearchLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchLibrarianButtonActionPerformed
               librarian searchLibrarian= new librarian();
               searchLibrarian.setSearchTF(SearchLibrarian.getText());
               searchLibrarian.SearchLibrarian();
               
                String add1=searchLibrarian.getLibrarianID();
                librarianID.setText(add1);
                String add2=searchLibrarian.getFirstName();
                librarianFN.setText(add2);
                String add3=searchLibrarian.getLastName();
                librarianLN.setText(add3);
                String add4=searchLibrarian.getUsername();
                librarianUN.setText(add4);
                String add5=searchLibrarian.getPassword();
                librarianP.setText(add5);
                 String add6=searchLibrarian.getEmailAddress();
                librarianEA.setText(add6);
                 String add7=searchLibrarian.getPhoneNumber();
                librarianPN.setText(add7);

    }//GEN-LAST:event_SearchLibrarianButtonActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    LoginInterface s= new LoginInterface();
       s.setVisible(true);
       dispose();

    }//GEN-LAST:event_logoutActionPerformed

    private void ExitTheSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitTheSystemActionPerformed
      System.exit(0);
    }//GEN-LAST:event_ExitTheSystemActionPerformed

    private void TotalBorrowedBookReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBorrowedBookReportActionPerformed
     book report=new book();
     report.ReportTotalNumberOFBorroedBook();
     int add1=report.getTotalBorrowedBook();
     String y = String.valueOf(add1);
     String display="hi";
     TFTRY.setText("The total Number of the Borrowed Books is as Displayed  Below:");
     ReportArea.setText(y);
    }//GEN-LAST:event_TotalBorrowedBookReportActionPerformed

    private void totalAvailableBooksReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAvailableBooksReportActionPerformed
      
        book report=new book();
     report.ReportTotalNumberOFAvailableBook();
     int add1=report.getTotalAvailableBook();
     String y = String.valueOf(add1);
     TFTRY.setText("The total Number of the Available Books is as Displayed  Below:");
     ReportArea.setText(y);
    }//GEN-LAST:event_totalAvailableBooksReportActionPerformed

    private void EditNewGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNewGuestActionPerformed
       guest editGuest=new guest();
        editGuest.setGuestID(guestID.getText());
        editGuest.setFirstName(firstName.getText());
        editGuest.setLastName(lastName.getText());
      
        editGuest.setGender(gender.getSelectedItem().toString());
        editGuest.setEmailAddress(emailAddress.getText());
        editGuest.setPhoneNumber(phoneNumber.getText());
        editGuest.setAddress(Address.getText());
        editGuest.EditGuest();
        updateGuesttable();
        
    }//GEN-LAST:event_EditNewGuestActionPerformed

    private void deleteGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGuestActionPerformed
       int p = JOptionPane.showConfirmDialog(null, "Are you Sure That you Want to delete the selected item", "delete" ,JOptionPane.YES_NO_OPTION);
        if(p==0){
       guest deleteGuest=new guest();
       deleteGuest.setGuestID(guestID.getText());
       deleteGuest.DeleteGuest();
       updateGuesttable();
        }
    }//GEN-LAST:event_deleteGuestActionPerformed

    private void searchGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGuestActionPerformed
           guest searchGuest=new guest();
               searchGuest.setSearchTF(searchGuestTF.getText());
               searchGuest.SearchGuest();
               
                String add1=searchGuest.getGuestID();
                guestID.setText(add1);
                String add2=searchGuest.getFirstName();
                firstName.setText(add2);
                String add3=searchGuest.getLastName();
                lastName.setText(add3);            
                String add4=searchGuest.getGender();
                gender.setSelectedItem(add4);
                 String add5=searchGuest.getEmailAddress();
                emailAddress.setText(add5);
                 String add6=searchGuest.getPhoneNumber();
                phoneNumber.setText(add6);  
                 String add7=searchGuest.getAddress();
                Address.setText(add7); 
    }//GEN-LAST:event_searchGuestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                BookID.setText("");
                BookISBN.setText("");
                BookTitle.setText("");
                BookAuthor.setText("");
                BookStatus.setSelectedItem("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                librarianID.setText("");
                librarianFN.setText("");
                librarianLN.setText("");
                librarianUN.setText("");
                librarianP.setText("");
                librarianEA.setText("");
                librarianPN.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                guestID.setText("");
                firstName.setText("");
                lastName.setText("");
           
                gender.setSelectedItem("");
                emailAddress.setText("");
                phoneNumber.setText("");  
                Address.setText("");       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookBTN;
    private javax.swing.JButton AddLibrarian;
    private javax.swing.JButton AddNewGuest;
    private javax.swing.JTextField Address;
    private javax.swing.JTextField BookAuthor;
    private javax.swing.JTextField BookID;
    private javax.swing.JTextField BookISBN;
    private javax.swing.JComboBox<String> BookStatus;
    private javax.swing.JTable BookTable;
    private javax.swing.JTextField BookTitle;
    private javax.swing.JButton DeleteBook;
    private javax.swing.JButton DeleteLibrarian;
    private javax.swing.JButton EditBook;
    private javax.swing.JButton EditLibrarian;
    private javax.swing.JButton EditNewGuest;
    private javax.swing.JMenuItem ExitTheSystem;
    private javax.swing.JTable GuestTable;
    private javax.swing.JTable LibrarianTable;
    private javax.swing.JTextArea ReportArea;
    private javax.swing.JTextField SearchLibrarian;
    private javax.swing.JButton SearchLibrarianButton;
    private javax.swing.JTextField TFTRY;
    private javax.swing.JButton TotalBooksReport;
    private javax.swing.JButton TotalBorrowedBookReport;
    private javax.swing.JButton deleteGuest;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField firstName;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField guestID;
    private javax.swing.JButton guestReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField librarianEA;
    private javax.swing.JTextField librarianFN;
    private javax.swing.JTextField librarianID;
    private javax.swing.JTextField librarianLN;
    private javax.swing.JTextField librarianP;
    private javax.swing.JTextField librarianPN;
    private javax.swing.JTextField librarianUN;
    private javax.swing.JMenuItem logout;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JButton searchGuest;
    private javax.swing.JTextField searchGuestTF;
    private javax.swing.JTextField searchTF;
    private javax.swing.JButton totalAvailableBooksReport;
    // End of variables declaration//GEN-END:variables
}
